simpeg/discretize

discretize/MeshIO.py
patch to ensure we are using `ints` as indices and shapes
=> read in UBC mesh size as ints, not floats

discretize/DiffOperators.py
- cache `aveF2CC`, `aveF2CCV`, `aveE2CC`, `aveE2CCV` as per #48 
- question: do we want to be also caching the components (eg. `aveFx2CC`, ...)? Currently we are, but I think this might be unnecessary. The components are called once more to get the regularization operators constructed, but are then cached there, so it is really only one more call
=> cache the averaging operators

docs/content/installing.rst
The page on "numpy for matlab users" has moved to: 
https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html
=> docs: update link for the numpy for matlab users page

discretize/View.py
- `".-"` is no longer valid for a linestyle input in matplotlib, it should instead be "-." (however, a solid line looks better anyways for the 1d).
=> minor update in plotGrid - linestyle 

.travis.yml
There was some weirdness happening with the pip installed from conda on py2.7. To mitigate this, I just set the build to use the native py27 pip for all dependencies. If Python version is 3.x then it uses conda to manage dependencies.
=> fix/py27: Fix the Travis build for Python 2.7

appveyor.yml, docs/conf.py, docs/examples/plot_cahn_hilliard.py
The link to the FiPy site is currently down causing the docs and new prs to fail (e.g. as in #130). I have replaced the link in the example to the FiPy github url for now.
=> docs: broken links

discretize/mixins/vtkModule.py, requirements_dev.txt
I recently added a ton of new features to [`vtki`](https://github.com/akaszynski/vtki) (the VTK interface Python package) that help make using just about any VTK data objects more intuitive/Pythonic. If `vtki` is available in your Python environment then these changes make using VTK data objects way easier. Here's a screenshot of what this currently looks like in a Jupyter notebook (creates static renderings but can also be interactive in a separate pop-up window). 
Also check out [this notebook](https://github.com/OpenGeoVis/PVGeo-Examples/blob/master/3.0%20-%20Using%20the%20vtkInterface%20Package.ipynb) to see more ways to use [`PVGeo`](https://github.com/OpenGeoVis/PVGeo), `discretize`, and [`vtki`](https://github.com/akaszynski/vtki). Below is a screenshot of a simple use case:
Some …
=> Add vtki support to make using VTK data objects more Pythonic

AUTHORS.rst
This fixes Mike Wathen's (@wathenmp) username link check in the docs which is causing builds to fail. I pulled the new username from the contributors page.
=> Fix failing docs builds

discretize/mixins/vtkModule.py
The code was already in `discretize`, these changes just make the function accessible to users to convert `vtkRectilinearGrid` objects to `TensorMesh` objects.
Needed this recently for a project - it was easiest to create my mesh in `vtki` and repeatedly visualize it while tweaking its size. Then I could convert it to `discretize` to use in an inversion.
For example (needs to be done in IPython)
```py
import vtki
from vtki import examples
import discretize
import numpy as np
p = vtki.BackgroundPlotter()
p.show_grid()
```
```py
topo = examples.download_st_helens().warp_by_scalar()
p.add_mesh(topo, name='topo')
```
```py
b = topo.bounds
xcoords = np.linspace(b[0], b[1], 50)
ycoords = np.linspace(b[2], b[3], 50)
zcoords = np.linspace(b[4]-5000, b[5], 50)
mesh = vtki.RectilinearGrid(xcoords, …
```
=> Add access for vtkToTensorMesh function

discretize/View.py
Small change to provide more flexibility for `plot_3d_slicer`. It now takes an optional `fig`-parameter (100% backwards compatible), in which one can provide an existing figure handle. The figure is cleared at every call, but no new figure is created. This can give some more flexibility, for instance in the use together with widgets.
Initiated upon an idea by @fourndo, who uses it for a Mag Tutorial:
where he used the figure handle to replace the YZ-plot with a data plot, and wrap it into a widget.
Code example: Now you can call
```
fig = plt.figure()
mesh.plot_3d_slicer(model, fig=fig)
```
where `fig` is an existing figure. And then you can do more funky stuff with your figure handle. It is sort of a convenience addition, as the same would be possible with:
```
fig = plt.figure()
tracker …
```
=> Add `fig`-parameter to `plot_3d_slicer`

discretize/View.py
Add `(x,y,z)lim` to limit the axis. It works with the interactive tools and the home-button will reset to the provided limits. Resolves #165.
=> Add `(x,y,z)lim` to plot_3d_slicer

discretize/TreeMesh.py, discretize/base/base_mesh.py, discretize/base/base_tensor_mesh.py, discretize/tree_ext.pyx, discretize/utils/codeutils.py, tests/base/test_basemesh.py, tests/base/test_tensor.py, tests/base/test_utils.py, tests/cyl/test_cyl.py, tests/tree/test_tree.py
update instantiation of basemesh so meshes can be formed from their serialized state, e.g.
```
mesh = discretize.BaseMesh.deserialize(mesh_json)
```
will have the value of `_n` stored, thus, `n` does not need to be provided on instantiation
=> serialization of basemesh 

discretize/TreeMesh.py, discretize/View.py, discretize/tree_ext.pyx
The problem of #184 is that the plotting classes are inherited by other classes, so they should always be available. The fix is therefore to move the `@requires` from the class level down to the function level. This should answer @rowanc1 question :wink: (https://github.com/simpeg/discretize/pull/156#discussion_r281029700).
This PR will close #184.
=> Resolving #184

.travis.yml, appveyor.yml, discretize/Tests.py, discretize/View.py, examples/plot_dc_resistivity.py, setup.py
This branch contains a few small bug fixes.
Mainly, it enables discretize to be installed on a system without NumPy present beforehand (for example when pip installing discretize). Resolve #51, Resolve #147
It also contains a small update to the curvilinear mesh view that updates that function to be in line with the other ``plotImage`` functions. Resolve #190 
Also note that this branch removes testing and automatic wheel building for python 2.7
=> Numpy build fix

discretize/View.py
Bugfix. Slicer failed if `xslice` was provided without a `yslice`, because of wrong comparison.
=> Bugfix slicer

discretize/MeshIO.py, tests/tree/test_tree_io.py
We can output models through the `writeUBC`. however I thought we might want, for symmetry with `TensorMesh`, also have the `writeModelUBC` function. Any thought appreciated.
=> add the `writeModelUBC` IO function for TreeMesh

docs/release/0.4.12-notes.rst, requirements_dev.txt, setup.py
Remove `pymatsolver` from `build_requires` in `setup.py`, as it is not required (keep requirements low).
=> Remove pymatsolver

discretize/MeshIO.py, discretize/TreeMesh.py, discretize/tree_ext.pyx, docs/release/0.4.13-notes.rst, docs/release/0.4.14-notes.rst, tests/tree/test_tree_io.py
Even though the set of meshes used by UBC does not include Quad Tree, it would be useful to add this to the IO. This PR will add QuadTree meshes to the readUBC, writeUBC, readModelUBC and writeModelUBC.
=> Create IO for 2D Tree mesh in UBC-like format

.travis.yml, discretize/CurvilinearMesh.py, discretize/Tests.py, discretize/TreeMesh.py, discretize/View.py, discretize/base/base_mesh.py, discretize/tree_ext.pyx, discretize/utils/meshutils.py, docs/release/0.4.14-notes.rst, docs/release/0.4.15-notes.rst, docs/release/index.rst, examples/plot_slicer_demo.py, examples/plot_streamThickness.py, tests/base/test_tensor_boundary_poisson.py, tests/tree/test_tree.py, tests/tree/test_tree_operators.py, tutorials/inner_products/1_basic.py, tutorials/mesh_generation/4_tree_mesh.py, tutorials/operators/1_averaging.py, tutorials/operators/2_differential.py, tutorials/pde/1_poisson.py, tutorials/pde/2_advection_diffusion.py
The `TreeMesh.plotImage` function will now respect the `norm` option for the `pcolorOpts` dictionary.
This allows us to make better LogScaled model plots.
=> Add ability to handle "norm" keyword in pcolorOpts on the TreeMesh

discretize/View.py
=> Fix Slicer matplotlib-warning.

discretize/CylMesh.py, discretize/DiffOperators.py, discretize/TreeMesh.py, discretize/View.py, discretize/base/base_mesh.py, discretize/base/base_tensor_mesh.py, discretize/mixins/vtkModule.py, discretize/tree_ext.pyx, discretize/utils/codeutils.py, discretize/utils/io_utils.py, discretize/utils/matutils.py, discretize/utils/meshutils.py, docs/conf.py, docs/release/0.5.1-notes.rst, examples/plot_cyl_mirror.py, examples/plot_slicer_demo.py, tests/base/test_operators.py, tests/base/test_utils.py, tests/base/test_volume_avg.py, tests/cyl/test_cylOperators.py
Patch for #221 and #222.
For some reason I was expecting allclose to return False if the arrays were of different length.
In addition, there are a few syntax fixes for comparisons to True/False which is generally frowned upon in pep8, and syntax fixes for comparisons to literals.
=> Syntax and bug fixes

.gitignore, discretize/mixins/mpl_mod.py
In the TreeMesh plot_image method defining the range_y does not result in the expected behaviour.
Instead of using range_y to define the limits of the plot it uses range_x.
I didn't mean to include the change to my .gitignore file in the pull request but don't know how to remove it now.
=> Correct the range_y in Tree plot_image

discretize/tests.py, tests/base/test_tests.py
I was thinking of adding the dot test to `emg3d`, but thought that maybe it lives better in `discretize`, alongside the `OrderTest` and `check_derivative`. As such it is available to any tool that uses `discretize`, including `SimPEG`.
In `SimPEG` there are dozens of places where the dot-test is defined. I think it would be better to only define it once, here in `discretize`, and use always the same definition (avoiding code repetitions and slightly different implementations). However, adding it in `discretize` means that we would probably have to wait at least for 2 minor releases before we can use it in `SimPEG`.
I draw a lot of inspiration from the implementation in PyLops, and we are reworking the `dottest` over there currently (https://github.com/PyLops/pylops/pull/335, …
=> Add dot product test.

discretize/mixins/mpl_mod.py, tests/base/test_interpolation.py
Calling `plot_slice` with a `TensorMesh` currently results in the following warning:
```
/path/to/conda/env/lib/python3.9/site-packages/discretize/base/base_tensor_mesh.py:785: FutureWarning: The zerosOutside keyword argument has been deprecated, please use zeros_outside. This will be removed in discretize 1.0.0
warnings.warn(
```
This is an internal problem, and should not happen.
=> zeros_outside

discretize/mixins/mpl_mod.py
We should allow numpy int's in the plotting, as matplotlib handels them just fine.
We could also clean up some of the code on the way, such as `int(np.argmi(...))` could be simplified with `np.argmin()`, as it returns a `np.int_`.
Currently it simply fails (for no good reasons). -- Thoughts? (Maybe we should not check at all, and let matplotlib fail if it doesn't work, duck typing.)
=> Allow np.int_

docs/_static/css/custom.css
This modifies the CSS sheet to do some fancy dark mode formatting of colors, and images to make things look nice in dark mode!
=> Dark mode theme for documentation

discretize/_extensions/tree.cpp, discretize/_extensions/tree.h, discretize/_extensions/tree.pxd, discretize/_extensions/tree_ext.pyx, discretize/tree_mesh.py, tests/tree/test_tree_balancing.py
This adds support to build tree meshes that are balanced along diagonals in addition to along axis directions.
This is equivalent to the types of meshes that the UBC-GIF codes create.
Without diagonal balancing:
With diagonal balancing:
=> Diagonal tree balance

discretize/_extensions/tree.cpp, discretize/_extensions/tree.h, discretize/_extensions/tree.pxd, discretize/_extensions/tree_ext.pyx, discretize/tree_mesh.py, discretize/utils/mesh_utils.py, tests/tree/test_refine.py, tutorials/mesh_generation/4_tree_mesh.py
This is intended to replace the functionality of the `refine_tree_xyz` utility, which will be marked as deprecated.
The new functions have slightly more intuitive inputs (in my opinion). They use the `level` argument to explicitly refer to the octree level, and `padding_cells_by_level` to refer to the amount of padding around the object.
The previous function split the padding descriptions into the `octree_levels` argument and the `octree_levels_padding`. The method of refining at specific levels is not intuitive and it was implied only by the length of the array passed to `octree_levels`, and not there values, as the name might imply.
~There is still missing tests~, but just wanted to get these out there for feedback on the inputs and descriptions in the documentation of these functions. …
=> Add new refine surface, bounding box, and point refine methods.

discretize/operators/differential_operators.py, discretize/operators/inner_products.py, discretize/tests.py, docs/conf.py, docs/release/0.8.1-notes.rst, docs/release/0.8.2-notes.rst, environment_test.yml, requirements_dev.txt
Small updates to documentation.
`DiffOperators` and `InnerProducts` now inherit `BaseMesh` so that we get proper doc string inheritance for those methods defined in them.
Also, conditionally sets which classes we want to show the full inherited members of (Only our primary mesh classes)
=> Documentation updates

docs/release/0.8.2-notes.rst, docs/release/0.8.3-notes.rst, docs/release/index.rst
=> 0.8.3 staging

discretize/_extensions/tree_ext.pyx, discretize/base/base_mesh.py, discretize/base/base_regular_mesh.py, discretize/base/base_tensor_mesh.py, discretize/cylindrical_mesh.py, discretize/mixins/mesh_io.py, discretize/mixins/mpl_mod.py, discretize/mixins/vtk_mod.py, discretize/operators/differential_operators.py, discretize/operators/inner_products.py, discretize/tree_mesh.py, discretize/utils/code_utils.py, discretize/utils/codeutils.py, discretize/utils/coordutils.py, discretize/utils/curvilinear_utils.py, discretize/utils/curvutils.py, discretize/utils/interputils.py, discretize/utils/matrix_utils.py, discretize/utils/matutils.py, discretize/utils/mesh_utils.py, discretize/utils/meshutils.py
=> Add stacklevel to warnings

discretize/_extensions/tree.cpp, setup.py
Switching to try_emplace for node, edge, and face creation in cpp tree_mesh backend.
=> Switch to try_emplace

discretize/tests.py, tests/base/test_tests.py, tests/base/test_utils.py
Changes check_derivative function to use assertions instead of returning True or False if the test passed or failed.
Will now raise an AssertionError if the tests fails, or return True if the test passed.
Also adds an `assert_expected_order` test function that doesn't use the `OrderTest` class. This is simpler to use with `pytests`'s parameterized tests.
=> Assert tests

discretize/base/base_tensor_mesh.py, discretize/curvilinear_mesh.py, discretize/operators/differential_operators.py, discretize/utils/matrix_utils.py
Update internal calls to the `make_boundary_bool` function, changing `dir` to `bdir`
=> Remove calls with deprecated dir argument

discretize/_extensions/tree_ext.pyx, discretize/base/base_mesh.py, discretize/operators/differential_operators.py, tests/base/test_basemesh.py, tests/base/test_operators.py, tests/tree/test_tree_interpolation.py
Fixes the averaging operator to actually do something that it describes. Before it was doing an odd operation that was only relevant to the boundary integrals, and even then only to coordinate aligned axes. Now it switches it to actually average things, and then changes it to the needed part for the boundary integral
=> change name and description of average edge to face

discretize/curvilinear_mesh.py, tests/boundaries/test_boundary_integrals.py
Implements the 2nd order accurate surface integral for the 3D curvilinear mesh. Now properly takes into account the edge basis function dotted with a vector defined on the faces.
=> Curvilinear vector boundary integral

discretize/cylindrical_mesh.py, tests/cyl/test_cylOperators.py
Adds the edge to face averaging operator for cylindrical meshes
=> Cyl average edge

discretize/tests.py
Improves the assertion error message in the tests.
=> Add message to assertion error in tests.

tutorials/pde/1_poisson.py, tutorials/pde/3_nodal_dirichlet_poisson.py
Adds a tutorial detailing how to solve a nodal Poisson problem with Dirichlet boundary conditions.
=> Nodal boundary example

discretize/mixins/mpl_mod.py
The behaviour changed with the advent of ipympl (Lab; modern Notebook), I think. Currently the scroll over a figure makes the notebook keep scrolling, so it is hard to scroll over a slicer-image through the volume.
This PR implements the fix suggested by Matplotlib (PR 235).
=> Capture scroll

discretize/_extensions/tree_ext.pyx, discretize/tree_mesh.py, tests/tree/test_tree.py
The new method returns the whole set of nodes in the mesh, including non-hanging and hanging nodes. It comes useful when working together with `cell_nodes`.
=> Add `total_nodes` method to TreeMeshes

.pre-commit-config.yaml
Unpin Python 3.10 in pre-commit configuration and use any available Python 3 interpreter. This fixes issues when the Python version in the environment is not 3.10.
=> Use any Python 3 in pre-commit

discretize/_extensions/tree_ext.pyx, environment_test.yml, setup.py
This updates the cython code for updated functionality in the new 3.0.0 release of cython
=> Add a noexcept clause to the wrapper function

environment_test.yml, requirements_style.txt
pin version of flake8 used to be consistent with the pre-commit configuration.
=> Pin flake8

discretize/tensor_mesh.py, tests/base/test_tensor.py
Add a new `cell_nodes` property to `TensorMesh` that mimics the one of `TreeMesh` returning the indices of the nodes that correspond to each cell in the mesh. Add tests for the new feature.
=> Add cell_nodes property to TensorMesh

discretize/unstructured_mesh.py
In file: unstructured_mesh.py, method: `__get_inner_product_projection_matrices`, a logical equality check operation was performed with the same operand on both sides. The comparison operation always returns either true or false. Such logical short circuits in code lead to unintended behavior. 
I think this was probably a typo as a similar check is done in a different way in many other parts of the same code. I suggested that the logical operation should be reviewed for correctness. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project …
=> Update a test expression to fix a logical short circuit

.git_archival.txt, .gitattributes
This should include information necessary for setuptools_scm in archives created from github.
Instructions came from:
[setuptools_scm documentation](https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives)
=> Add export config for git archives

azure-pipelines.yml, meson.build, pyproject.toml
Makes use of the `cibuildwheel` tool for making pre-built wheels for many different operating systems on azure.
=> CIbuildwheel

docs/release/0.9.1-notes.rst, docs/release/index.rst
=> Add Release Notes for 0.10.0

docs/_static/versions.json, docs/conf.py
Apparently... (and this is not well documented), for the pydata-sphinx-theme to display the development banner either:
* the string `dev`, `rc`, or `pre` must appear in the "version" for the matcher
* or the version must compare greater than the preferred version.
So this just gives the main branch a `dev` version in the matcher, and also makes the `json_url` point to the version on `main`
=> display dev doc banner

discretize/unstructured_mesh.py, docs/content/additional_resources.rst, tests/simplex/test_operators.py
Change projection caching to depend on both the projection type and the `with_volume` kwarg.
(And update broken links in the docs. The python-for-scientists site was moved to pyzo.)
=> Fix caching of internal projection matrices

.ci/azure/setup_miniconda_macos.sh, .ci/azure/test.yml
macos-latest images on azure no longer have conda by default
=> Fix macos-latest build

.github/workflows/build_distributions.yml, README.rst, discretize/base/base_tensor_mesh.py, discretize/mixins/mpl_mod.py, discretize/utils/mesh_utils.py, docs/conf.py, docs/release/0.11.0-notes.rst, docs/release/index.rst, examples/plot_image.py
Staging for the 0.11.0 Release
=> 0.11.0 Release Notes

discretize/tests.py, tests/base/test_tests.py
When someone runs a test that would randomly initialize a random number generator from `pytest` or `nosetest`, issue a warning recommending setting the seed for repeatable tests.
This checks by using stack inspection looking for either `_pytest.` or `nose.`
=> Warn for non-repeatable random tests in a testing environment

discretize/tests.py, docs/_static/versions.json, docs/content/installing.rst, docs/release/0.11.1-notes.rst, docs/release/index.rst, examples/README.txt, pyproject.toml, tests/base/test_tests.py
Staging for the 0.11.1 bugfix release
=> Staging for 0.11.1

discretize/utils/code_utils.py, tests/base/test_utils.py
Fix for is_scalar to support arbitrary dimensional numpy arrays
=> improve scalar test to handle arbitrary dimensional ndarrays

discretize/mixins/mesh_io.py, discretize/mixins/mpl_mod.py, discretize/tree_mesh.py, discretize/utils/mesh_utils.py, tests/tree/test_tree_io.py
Set `diagonal_balance=False` when creating a `TreeMesh` after reading a UBC file in `read_UBC`. This prevents raising the future warning related to the default value of `diagonal_balance`. Add test that checks that no warning is being raised by that method.
=> Set no diagonal balance when reading UBC tree meshes

discretize/tree_mesh.py
Add missing space between "have" and "previously", fix spelling in "behavior".
=> Fix small typos in diagonal_balance warning

discretize/tests.py
https://github.com/simpeg/discretize/pull/384 popped up as warning in my tests, where is saw the missing white spaces ("berepeatable" and "isnot"):
```
/home/dtr/Codes/emg3d/tests/test_simulations.py:959: UserWarning: You are running a pytest without setting a random seed, the results might not berepeatable. For repeatable tests please pass an argument to `random seed` that isnot `None`.
discretize.tests.assert_isadjoint(
```
=> Fix formatting new warning

LICENSE, docs/_static/versions.json, docs/conf.py, docs/release/0.11.2-notes.rst, docs/release/index.rst
Staging for the v0.11.2 release
=> v0.11.2 staging

discretize/_extensions/tree_ext.pyx, discretize/tree_mesh.py, tests/tree/test_safeguards.py
Raise errors when trying to access some of the `TreeMesh` properties before it gets finalized. The properties that got the safeguards are the ones that generate an ill-defined mesh if they are accessed before finalizing the mesh. Add tests to check if the errors are correctly raised.
Fixes #293 #392
A property generate an ill-defined mesh if accessing it before the mesh gets
finalized modifies the ultimate definition of the mesh.
For example, an offending property `prop_name` would make the following code to
generate `property_value` and `expected_value` with non-equivalent values.
Therefore, just accessing `prop_name` changes the definition of the mesh.
```python
mesh = TreeMesh(...)
mesh.refine_ball(..., finalize=False)
mesh.finalize()
expected_value = mesh.prop_name
mesh = …
```
=> Add safeguards to TreeMesh properties

docs/_static/versions.json, docs/release/0.11.3-notes.rst, docs/release/index.rst
Staging for 0.11.3 bugfix release
=> 0.11.3 staging

.ci/environment_test.yml, docs/_static/versions.json, pyproject.toml
Current doc builds fail combing the pinned pydata-sphinx-theme with the most recent sphinx, so let's bump and pin both
=> bump sphinx and pydata-sphinx to more recent versions
