discretize/utils/matutils.py, tests/base/test_utils.py
- give the `Identity` class a `T` and `transpose`
- return `self` when transposing a `Zero`
=> give the Identity a transpose

README.rst
add 
- codacy: https://www.codacy.com/app/lindseyheagy/discretize/dashboard
- quantified code: https://www.quantifiedcode.com/app/project/97126041a7e7400fbf1c5555bed514dc
to the README
=> add codacy and quantified code

discretize/utils/meshutils.py, tests/base/test_utils.py
- port over fixes that were made in SimPEG extract core mesh
=> Extract Core Mesh

discretize/TreeMesh.py
this is only style cleanup on the TreeMesh_CellGrad PR #72
=> style cleanup

README.rst
As I adjusted simpeg/simpeg I thought I can do it for simpeg/discretize as well.
=> Add Zenodo

discretize/BaseMesh.py, discretize/CylMesh.py, discretize/InnerProducts.py, discretize/Tests.py, discretize/View.py, discretize/utils/curvutils.py, discretize/utils/meshutils.py, docs/conf.py, docs/content/installing.rst, docs/content/view.rst, docs/index.rst
- make sure slicer is documented
- cleanup including using `numpy.ndarray` as the type (rather than `numpy.array` which is not a documented type)
=> add Slicer to docs, some light docs cleanup

AUTHORS.rst
=> Adding myself to authors list

discretize/mixins/vtkModule.py
=> Change model array shape check for VTK mixin

requirements_dev.txt
=> Restrict Sphinx<2.0

AUTHORS.rst
=> add to contributors

tutorials/mesh_generation/4_tree_mesh.py
It is supposed to be `tree`, not `tensor`, right?
=> Fix a typo in tutorial: Update 4_tree_mesh.py

discretize/DiffOperators.py, discretize/base/base_mesh.py, discretize/mixins/vtkModule.py, discretize/utils/__init__.py, discretize/utils/meshutils.py, docs/api/index.rst, docs/content/installing.rst, docs/index.rst, docs/release/0.4.12-notes.rst, docs/release/index.rst, tests/base/test_utils.py
Addresses issue #197 
Cleanup and speed up the `surface2ind_topo` function from `simpeg.utils.modelutils`
=> Refine tree xyz

.travis.yml, docs/release/0.4.12-notes.rst
just consolidating a few travis tests
=> consolidating tests on travis

discretize/MeshIO.py
=> Bug fix for 2D mesh read in.

docs/release/0.4.12-notes.rst
Updating release notes, will soon be tagging a 0.4.12 release on master.
=> update release notes

discretize/MeshIO.py, docs/release/0.4.13-notes.rst
After some small discussion with Sarah Devriese, We identified a bug in the UBC 2d model read in.
Also this is demonstrating creating a PR from my own private repo!
=> small bug fix for 2D UBC TensorMesh model readin

discretize/TreeMesh.py, discretize/View.py, discretize/tree_ext.pyx, docs/release/0.4.15-notes.rst, docs/release/index.rst
I had a small bug in the deprecations for vType....
=> Fix bug in deprecated vType

.travis.yml, docs/content/installing.rst, docs/release/0.5.0-notes.rst, docs/release/index.rst, setup.py
=> 0.5.0 release notes and requirements update

discretize/_extensions/tree_ext.pyx, discretize/base/mesh_io.py, discretize/cylindrical_mesh.py, discretize/operators/differential_operators.py, discretize/tree_mesh.py, docs/release/0.6.1-notes.rst, docs/release/index.rst
Switch more internal storage matrices to match outer descriptions, and promote some stencils to publicly accesible
=> Quick Patch for stencil matrices

discretize/base/base_mesh.py, discretize/base/base_tensor_mesh.py, discretize/base/mesh_io.py, discretize/cylindrical_mesh.py, discretize/mixins/mpl_mod.py, discretize/mixins/vtk_mod.py, discretize/operators/inner_products.py, discretize/tree_mesh.py, discretize/utils/code_utils.py, discretize/utils/codeutils.py, discretize/utils/coordutils.py, discretize/utils/curvilinear_utils.py, discretize/utils/curvutils.py, discretize/utils/interputils.py, discretize/utils/matrix_utils.py, discretize/utils/matutils.py, discretize/utils/mesh_utils.py, discretize/utils/meshutils.py, docs/release/0.6.2-notes.rst, docs/release/index.rst, examples/plot_quadtree_hanging.py
Changes FutureWarnings back to DeprecationWarnings
=> Deprecate warnings

docs/release/0.6.2-notes.rst, docs/release/0.6.3-notes.rst, docs/release/index.rst
=> 0.6.3 release notes

discretize/operators/differential_operators.py, docs/release/0.7.0-notes.rst, docs/release/index.rst
=> 0.7.0 release notes

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, README.rst, discretize/base/base_mesh.py
a bug fix for 1D mesh closest index searches.
=> ensure the grid locations are (N x dim) happens in 1D

discretize/operators/differential_operators.py
Looks to be a small bug in the 2D edge curl operator, that wasn't noticed before
This should make it more accurate.
=> update 2D edge curl operator to properly go from 2D edges to Z-faces

discretize/_extensions/tree_ext.pyx
=> fix faces property of TreeCell

discretize/_extensions/tree_ext.pyx
Adding Linear interpolation on TreeMesh between cells with the same level.
Previously: 
- Cell-Centered interpolation was essentially a containing cell lookup,
- Face interpolation was linear in the direction of the face normal, but nearest neighbor in the other two direction
- Edge interpolation was nearest neighbor in the direction tangent to the edge, and linear in the other two directions
After Updating Interpolation:
- Cell-centered linear in each direction between adjacent cells with the same level in that direction, nearest otherwise
- Faces linear in direction of face normal, linear in each other direction if that adjacent cell is the same level, nearest otherwise
- Edges linear in two directions tangent to the edge, linear in tangent direction if cell is the same level, nearest …
=> Updating TreeMesh Interpolation

discretize/Tests/__init__.py, discretize/View.py, discretize/base/base_mesh.py, discretize/base/base_regular_mesh.py, discretize/base/base_tensor_mesh.py, discretize/cylindrical_mesh.py, discretize/mixins/mesh_io.py, discretize/mixins/mpl_mod.py, discretize/mixins/vtk_mod.py, discretize/operators/differential_operators.py, discretize/operators/inner_products.py, discretize/tensor_mesh.py, discretize/tests.py, discretize/tree_mesh.py, discretize/unstructured_mesh.py, discretize/utils/code_utils.py, discretize/utils/codeutils.py, discretize/utils/coordinate_utils.py, discretize/utils/coordutils.py, discretize/utils/curvilinear_utils.py, discretize/utils/curvutils.py, discretize/utils/interpolation_utils.py, discretize/utils/interputils.py, discretize/utils/matrix_utils.py, discretize/utils/matutils.py, discretize/utils/mesh_utils.py, discretize/utils/meshutils.py, docs/release/0.8.0-notes.rst, docs/release/index.rst
Here are the release notes, as well as the deprecation switchover for discretize.
=> 0.8.0 Release

discretize/cylindrical_mesh.py, tests/cyl/test_cylOperators.py
Add the nodal gradient operator (and tests) for the cylindrical mesh
=> Nodal_Gradient for the CylindricalMesh

.azure-pipelines/azure-pipelines-win.yml, discretize/_extensions/tree_ext.pyx, tests/tree/test_tree.py
Fix for generating list of cell nodes in 3D on the TreeMesh
(Also adds a test for verification)
=> Cell node tree

docs/release/0.8.1-notes.rst, docs/release/index.rst, setup.py
=> 0.8.1 Release

discretize/mixins/__init__.py, discretize/mixins/mesh_io.py, docs/release/0.8.2-notes.rst, docs/release/index.rst
Small bug fix for importing the `importlib.util` package to check for installed packages.
=> Import lib fix

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, azure-pipelines.yml, docs/conf.py, docs/release/0.4.12-notes.rst, docs/release/0.4.13-notes.rst, docs/release/0.4.14-notes.rst, docs/release/0.4.15-notes.rst, docs/release/0.5.0-notes.rst, docs/release/0.5.1-notes.rst, docs/release/0.6.0-notes.rst, docs/release/0.6.1-notes.rst, docs/release/0.6.2-notes.rst, docs/release/0.6.3-notes.rst, docs/release/0.7.0-notes.rst, docs/release/0.7.1-notes.rst, docs/release/0.7.2-notes.rst, docs/release/0.7.3-notes.rst, docs/release/0.7.4-notes.rst, docs/release/0.8.0-notes.rst, docs/release/0.8.1-notes.rst, docs/release/0.8.2-notes.rst, environment_test.yml, requirements_dev.txt, setup.py, tests/docs/test_docs.py
Updates the testing environment to be created using an environment.yml
=> Testing environment updates

docs/_static/css/custom.css
Updates the doc page style sheet to be consistent with the newer pydata theme template
=> update doc page style sheet

environment_test.yml
Add `black`, `flake8` and some flake8 plugins to the `environment_test.yml` file.
=> Add black, flake8 and flake8 plugins to environment file

discretize/unstructured_mesh.py
Stash created operators on the `SimplexMesh`.
=> Simplex stashing

docs/conf.py
Attempting to solve the `trame` errors (without including it in the environment at the moment).
=> Configure pyvista for doc builds

README.rst, docs/conf.py
Update links in `README.rst` and `docs`.
=> Replace Slack links for Mattermost links

.ci/environment_test.yml, pyproject.toml
Bumps to most recent  pydata_sphinx_theme version.
=> Bump pydata_sphinx_theme version to 0.15.4

discretize/tree_mesh.py, tests/tree/test_tree.py
Using this PR to fix any bugs identified while testing downstream packages
=> Outstanding bugfixes.

discretize/utils/matrix_utils.py, tests/base/test_utils.py
Adds `__bool__` dunders for both the `Zero` matrix and `Identity` matrix, such that they would follow expected truthiness evaluations:
* ``bool(Zero()) is False``
* ``bool(Identity()) is True``
=> Implement truthiness for Zero and Identity

discretize/_extensions/tree_ext.pyx
Fixes for deprecated behavior in Cython
=> Switches to libc math import

.ci/azure/setup_env.sh, .ci/azure/test.yml, .ci/environment_test_bare.yml, .github/workflows/build_distributions.yml, pyproject.toml
=> Updates for cibuildwheel
